Fix fallthrough to the next plugin when suitable
coredns/kubernetai pull request #40
Opened 2021-05-06 22:00 UTC by t0rr3sp3dr0

Fixes #39

This patch disables fallthrough on all internal instances of the Kubernetes plugin and lets Kubernetai handle it instead.

Previously the last Kubernetes plugin instance would try to fallthrough and fail as no `Next` plugin instance was set.

2021-05-06 22:32 UTC, t0rr3sp3dr0 commented
CicleCI was complaining about missing entries on `go.sum`, so I executed `go mod tidy` and committed the changes.

![image](https://user-images.githubusercontent.com/7753096/117373283-542af080-aea1-11eb-925d-47506b82ea5d.png)

2021-05-06 22:42 UTC, t0rr3sp3dr0 commented
@chrisohaver, the test is failing because there is no `go.sum` on https://github.com/coredns/ci

2021-05-06 22:46 UTC, t0rr3sp3dr0 commented
Someone already submitted a PR that creates `go.sum` on the repository, but it hasn't been merged: https://github.com/coredns/ci/pull/139

2021-05-06 23:02 UTC, rajansandeep reviewed
I've opened https://github.com/coredns/kubernetai/pull/41 to fix CI.

2021-05-06 23:44 UTC, t0rr3sp3dr0 commented
I've reverted 0bd9a58 as it wasn't needed.

2021-05-07 13:37 UTC, chrisohaver commented
I think this can be even further simplified, by chaining the Kubernetes instances to each other, and setting `Next` on the final instance to the next plugin in the chain (in Add Plugin).  This would allow us to simply call ServeDNS on the first Kubernetes instance, and let the Kubernetes instances themselves handle the fallthrough logic and next plugin chaining.

e.g. something like ...

https://github.com/coredns/kubernetai/compare/master...chrisohaver:fallthufix

2021-05-07 16:57 UTC, t0rr3sp3dr0 commented
@chrisohaver, I've followed your suggestion with some changes.

The linking procedure between one Kubernetes instance and its successor was moved out of the `Parse` function into the `setup` function.

Additionally, a check was added to ensure that at least one Kubernetes instance always exists. Previously it wasn’t a problem as we used for-loops to iterate over the slice, but now we have direct references to the first element of the slice.

2021-05-07 18:14 UTC, chrisohaver commented on plugin/kubernetai/setup.go
> +	if len(k8i.Kubernetes) == 0 {
Can this condition ever occur?

2021-05-07 18:14 UTC, chrisohaver commented on plugin/kubernetai/setup.go
> +		// set Next of the previous kubernetes stanza to the current stanza
```suggestion
		// set Next of the previous kubernetes instance to the current instance
```

2021-05-16 22:51 UTC, t0rr3sp3dr0 commented
@chrisohaver, I've implemented the tests.

2021-05-17 12:23 UTC, chrisohaver approved these changes
Lgtm Thanks!

2021-05-17 12:29 UTC, chrisohaver requested changes
New tests failed.

2021-05-17 17:52 UTC, t0rr3sp3dr0 commented
I'm not able to reproduce the error. On my machine, the tests are passing. It looks like the tests on CI are trying to connect to the fake API servers that I've specified

![image](https://user-images.githubusercontent.com/7753096/118533911-045cec80-b71f-11eb-8e44-ed9491bba4ea.png)

2021-05-17 17:58 UTC, t0rr3sp3dr0 commented
Using the same command as the workflow also doesn't throw any error on my side.

![image](https://user-images.githubusercontent.com/7753096/118535002-4c304380-b720-11eb-9638-8a1fc6a84135.png)

2021-05-17 18:06 UTC, t0rr3sp3dr0 commented
I've rebased my branch and now I'm able to reproduce the problem. There was some dependency upgrade on master that is making the test fail. I'll work on it.

2021-05-17 18:27 UTC, chrisohaver commented
@t0rr3sp3dr0 I suspect it's due to a bug fixed in coredns/coredns#4492, which is not released yet.

I think we can ignore the failure for now.  It should pass once coredns 1.8.4 is released, and we bump the dependency here.

2021-05-17 18:30 UTC, chrisohaver approved these changes
Thanks for the fix and tests!

2021-05-17 18:31 UTC, merged